### PR TITLE
R ccontroller

### PR DESCRIPTION
**Pull request by DAG00DAG33**
As far as I know, RCcontroler is the latest working branch. It has the code from the EVGrandPrix 2022 competition plus the security fixes for the steering PID done during the Summer. Meanwhile, the main branch is outdated. I think it would be a good idea to put the latest code on main, and then I will make a branch to document and comment on the code. Also, another branch could be done to make the new updates to the code for the new steering.

### CODE REVIEW

**Comment by HaoruXue** [comment]
Will look into reviewing this.

Is anyone responsible for checking if all the codes here are functional on the latest hardware?

**Comment by DAG00DAG33** [comment]
@HaoruXue 
Thank you
@jvfausto and I talked the other day and made sure it is the latest version.
I believe it hasn't been tested on hardware though (besides when the pushes were made, but the pushes are quite old).
It could be a good idea to test it on the hardware, but I believe the steering mechanism has been changed, which is one of the crucial parts, so there isn't much to test.
That is the reason I want to make the merge in the first place, so all the changes for the new steering can be done on a new branch. Also, I want to create a new branch for documentation purposes. But I think it would be cleaner if these new branches branch out of the master,

**Comment by HaoruXue** [comment]
Sure we can do that, but could you do a basic clean up on things like

1. commented out codes that are no longer needed
2. maintainer information on the file header
3. basic code style consistancies (variable and function naming conventions, etc.)

Then we can update the master branch with this branch, and solve any further styling problems later on by opening up a follow-up issue.

**Comment by chxp82q** [comment]
@DAG00DAG33 I merged the RCcontroller branch into the ece191-team-dev branch and have done changes to get CAN communication working with the two VESCs.

The code that is active on our branch has been tested on hardware, however isn't the quality of code I would consider submitting a PR for to the master branch.

Our branch still needs basic cleaning, important comments, and sensor polling cleanup. For now, I suggest closing this PR and wait for one from ece191-team-dev.

**Comment by mdlopezme** [comment]
Closed pull request due to inactivity. If anyone is interested in reopen, just DM.

**Pull request closed without merging**
